	vw = 1, int = 3;
	tmpobjid = CreateDynamicObject(2789, 353.42429, 174.1004, 1011.9299,   0.00000, 0.00000, 90.00000, vw, int);
	SetDynamicObjectMaterialText(tmpobjid, 0, Main_Color"ogrm-project.ru", 140, "Calibri", 95, 1, 0xFFFFFFFF, 0, 1);

	AdminBoard = CreateDynamicObject(2789, 353.42429, 162.34560, 1011.04138,   0.00000, 0.00000, 90.00000, vw, int);
	SetDynamicObjectMaterialText(AdminBoard, 0, Main_Color"Модераторы", 140, "Calibri", 26, 1, 0xFFFFFFFF, 0, 1);

	LeaderBoard = CreateDynamicObject(2789, 353.42429, 168.24561, 1011.04138,   0.00000, 0.00000, 90.00000, vw, int);
	SetDynamicObjectMaterialText(LeaderBoard, 0, Main_Color"Лидеры онлайн", 140, "Calibri", 26, 1, 0xFFFFFFFF, 0, 1);

	PlayerBoard = CreateDynamicObject(2789, 353.42429, 179.9566, 1011.04138,   0.00000, 0.00000, 90.00000, vw, int);
	SetDynamicObjectMaterialText(PlayerBoard, 0, Main_Color"Топ игроков", 140, "Calibri", 26, 1, 0xFFFFFFFF, 0, 1);

	DonateBoard = CreateDynamicObject(2789, 353.42429, 185.8566, 1011.04138,   0.00000, 0.00000, 90.00000, vw, int);
	SetDynamicObjectMaterialText(DonateBoard, 0, Main_Color"Топ донатов", 140, "Calibri", 26, 1, 0xFFFFFFFF, 0, 1);