	new tmpobjid, vw = 1, int = 15;
	tmpobjid = CreateDynamicObject(19805, 2227.485595, -1137.106201, 1030.638305, 0.000000, 0.000000, 0.000000, vw, int); 
	SetDynamicObjectMaterialText(tmpobjid, 0, Color_White"ƒобро пожаловать на сервер\n"Main_Color Project_Name Color_White"\n\n\n\
	"Color_White"ћы рады видеть вас на нашем проекте\n\
	"Color_White"и надеемс€, что вы\n\
	"Color_White"проведете свое врем€ с удовольствием\n\
	"Color_White"ѕервым делом\n\
	"Color_White"мы рекомендуем сходить в мэрию\n\
	"Color_White"и получить лицензии\n\
	"Color_White"¬ дальнейшем они вам очень сильно пригод€тс€!\n\n\
	"Color_White"¬ данный момент, наш игровой сервер находитьс€\n\
	"Color_White"в разработке.\n\
	"Color_White"¬ы можете следить за разработкой\n\
	"Color_White"на нашем сайте.\n\
	"Color_White"“ам же, ¬ы можете предложить свои идеи\n\
	"Color_White"дл€ сервера.\n\
	"Color_White"—айт сервера - ogrm-project.ru", 140, "Calibri", 26, 1, 0xFFFFFFFF, 0x00000001, 1);
	
	tmpobjid = CreateDynamicObject(3077, 2226.035146, -1149.614135, 1024.726806, 0.000000, 0.000000, 90.999893, vw, int);
	SetDynamicObjectMaterialText(tmpobjid, 1, "-", 140, "Calibri", 26, 1, 0, 0, 1);
	SetDynamicObjectMaterialText(tmpobjid, 0, "-", 140, "Calibri", 26, 1, 0x00000002, 0x00000002, 1);
	tmpobjid = CreateDynamicObject(3077, 2226.025146, -1149.614135, 1024.726806, 0.000000, 0.000000, 90.999893, vw, int); 
	SetDynamicObjectMaterialText(tmpobjid, 0, "Ќа нащем сервере есть\n\
	"Color_White"несколько различных организаций\n\
	"Color_White"¬ы сами можете выбрать кем хотите стать\n\n\n\
	"Color_White"¬ступить в банду или мафию\n\
	"Color_White"и стать частью преступной групировки.\n\
	"Color_White"√рабить и убивать ради собственного благополучи€\n\n\
	"Color_White"¬ступить в государственную организацию\n\
	"Color_White"и встать на сторону защиты правопор€дка,\n\
	"Color_White"нести закон в массы\n\n\
	"Color_White"–ешать вам!\n\n\
	"Color_White"ѕри€тной игры на сервере "Main_Color Project_Name, 140, "Calibri", 26, 1, 0xFFFFFFFF, 0x00000002, 1);
	
	tmpobjid = CreateDynamicObject(3077, 2216.317871, -1146.639047, 1024.716796, 0.000000, 0.000000, 0.000000, vw, int);
	SetDynamicObjectMaterialText(tmpobjid, 1, "-", 140, "Calibri", 26, 1, 0, 0, 1);
	SetDynamicObjectMaterialText(tmpobjid, 0, "-", 140, "Calibri", 26, 1, 0x00000002, 0x00000002, 1);
	tmpobjid = CreateDynamicObject(3077, 2216.317871, -1146.649047, 1024.716796, 0.000000, 0.000000, 0.000000, vw, int); 
	SetDynamicObjectMaterialText(tmpobjid, 0, Color_White"¬ы можете использовать чат на клавишу [F6]\n\
	"Color_White"дл€ общени€ с другими игроками\n\
	"Color_White"или использовани€ команд\n\n\n\
	"Main_Color"/main\n\
	"Color_White"универсальна€ команда,\n\
	"Color_White"вызывающа€ меню вашего коммуникатора\n\
	"Color_White"котора€ позвол€ет:\n\
	"Color_White"просматривать важную информацию о сервере\n\
	"Color_White"“ам вы можете найти информацию\n\
	"Color_White"о вашем персонаже, командах сервера и\n\
	"Color_White"местоположении тех или иных мест.\n\n\
	"Color_White"ѕри€тной игры на сервере "Main_Color Project_Name, 140, "Calibri", 26, 1, 0xFFFFFFFF, 0x00000002, 1);
	
	CreateDynamicObject(11714, 2228.95630, -1150.51294, 1030.02124,   0.00000, 0.00000, 180.00000, vw, int);